"https://dougblack.io/words/a-good-vimrc.html START


"Necessary for cool features of vim
set nocompatible

" Mouse support only in normal mode
set mouse=n

" https://github.com/numirias/security
set nomodeline

"custom (leader) shortcuts
let mapleader=" "       " leader is space

" Plugins
" Automatic installation of vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')
" Plug 'itchyny/lightline.vim'                                                        " Nice bar at the bottom
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-repeat'                                                             " Repeatable plugins
Plug 'tpope/vim-commentary'                                                         " Commenting with 'gc'
Plug 'jiangmiao/auto-pairs'                                                         " '' () [] {}
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }                   " PlugInstall and PlugUpdate will clone fzf in ~/.fzf and run the install script
Plug 'preservim/nerdtree'                                                           " Directory browser
Plug 'dhruvasagar/vim-vinegar'                                                      " - to open NERDTree inside split
Plug 'mbbill/undotree'                                                              " Undotree visualisation
Plug 'airblade/vim-gitgutter'                                                       " Git changes in gutter
Plug 'tpope/vim-obsession'                                                          " Session Management
Plug 'sheerun/vim-polyglot'
call plug#end()


" Plugin specific stuff
let g:sessions_dir = '~/vim-sessions'
exec 'nnoremap <Leader>ss :Obsession ' . g:sessions_dir . '/*.vim<C-D><BS><BS><BS><BS><BS>' 
nnoremap <Leader>sf :Obsession<CR>                                                  

"colors
syntax enable           " enable syntax processing

"tabs
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

"UI
set number relativenumber           " show line numbers
"Line number toggle
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
augroup END

set showcmd             " show command in bottom bar
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

"searching
set incsearch           " search as characters are entered

"movement
"move vertically by visual line
nnoremap j gj
nnoremap k gk

"highlight last inserted text
nnoremap gV `[v`]

"toggle gundo
nnoremap <leader>u :UndotreeToggle<CR>

"finding files
set path+=**

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
