"https://dougblack.io/words/a-good-vimrc.html START


"Necessary for cool features of vim
set nocompatible

" Mouse support only in normal mode
set mouse=n

" https://github.com/numirias/security
set nomodeline

" set mapleader 
let mapleader=" "       " leader is space

"""""""""""""""""""" Plugins

" Automatic installation of vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif


call plug#begin('~/.vim/plugged')
 " Status Line
Plug 'vim-airline/vim-airline'
 " Repeatable plugins
Plug 'tpope/vim-repeat'                                                            
 " Commenting with 'gc'
Plug 'tpope/vim-commentary'                                                        
 " '' () [] {}
Plug 'jiangmiao/auto-pairs'                                                        
 " PlugInstall and PlugUpdate will clone fzf in ~/.fzf and run the install
 " script
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }                  
 " Directory browser
Plug 'preservim/nerdtree'                                                          
 " - to open NERDTree inside split
Plug 'dhruvasagar/vim-vinegar'                                                     
 " Undotree visualisation
Plug 'mbbill/undotree'                                                             
 " Git changes in gutter
Plug 'airblade/vim-gitgutter'                                                      
 " Session Management
Plug 'tpope/vim-obsession'                                                         
 " Syntax highlighting
Plug 'sheerun/vim-polyglot'
 " Python PEP8 indentation 
Plug 'Vimjas/vim-python-pep8-indent'
 " Linting
Plug 'dense-analysis/ale'
call plug#end()


"""" Plugin options/config

" vim-obsession
let g:sessions_dir = '~/vim-sessions'
exec 'nnoremap <Leader>ss :Obsession ' . g:sessions_dir . '/*.vim<C-D><BS><BS><BS><BS><BS>' 
nnoremap <Leader>sf :Obsession<CR>                                                  

" FZF
nnoremap <Leader>o :FZF<CR>
nnoremap <Leader>O :FZF ~<CR>

" ALE
" Python Linting
let g:ale_fixers = {'python': ['autopep8']}
let g:ale_linters = {'python': ['pylint']}
let g:ale_lint_on_enter = 1              " Lint on Open
let g:ale_lint_on_save = 1               " Lint on Save
let g:ale_lint_on_text_changed = 'never' " Don't lint dynamically

"""" /Plugin options/config

"colors
syntax enable           " enable syntax processing

"tabs
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

"UI
set number relativenumber           " show line numbers
"Line number toggle
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
augroup END

set showcmd             " show command in bottom bar
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

"searching
set incsearch           " search as characters are entered

"movement
"move vertically by visual line
nnoremap j gj
nnoremap k gk

"toggle gundo
nnoremap <leader>u :UndotreeToggle<CR>

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"move auto-generated files to .vim folder
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" 88 char ruler
set colorcolumn=88
highlight ColorColumn ctermbg=233

